apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: memos-db-secret
  namespace: memos
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: memos-db-secret
    creationPolicy: Owner
  data:
    - secretKey: MEMOS_DSN
      remoteRef:
        key: memos-db-instance-db-password
        property: dsn
  