apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: monitoring
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  rules:
    - host: grafana.aamir-memos.co.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: memos-grafana
                port:
                  number: 80
  tls:
    - hosts:
        - grafana.aamir-memos.co.uk
      secretName: grafana-tls
      