apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 9.7.1
    helm:
      values: |
        server:
          extraArgs:
            - --insecure

          service:
            type: ClusterIP
            servicePort: 80
            serviceTargetPort: 80

          ingress:
            enabled: true
            ingressClassName: traefik
            hostname: argocd.aamir-memos.co.uk
            path: /
            pathType: Prefix

            annotations:
              traefik.ingress.kubernetes.io/service.serversscheme: http

            tls: []

        configs:
          cm:
            url: https://argocd.aamir-memos.co.uk

          rbac:
            policy.default: role:read-only

  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true